### ISSUE TITLE
Visual Feedback for Throttle Min and Max Calibration Broken

### ISSUE THREAD

**Issue by spindriftDev** [diydrones/MissionPlanner#897] opened 2015-06-08 17:42 UTC
While calibrating the radio, Mission Planner shows red lines illustrating the measured minimum and maximum recorded PWM input for each radio channel. This visual feature appears to be broken for the throttle channel - the red lines do not move. Performing calibration works correctly, and the actual/correct minimum and maximum throttle values are recorded in the config file. However, these correct throttle bounds are not correctly displayed on the screen.

**Comment by meee1** [comment] 2015-06-08 22:39
duplicate of
#896
and
#883
so closing

**Closed by meee1** 2015-06-08 22:39 UTC
