### ISSUE TITLE
Flight Modes

### ISSUE THREAD

**Issue by howeson1** [diydrones/MissionPlanner#1079] opened 2015-12-11 20:17 UTC
Please would there be an option to change the flight mode channel on copters? I know this is possible on planes and rovers so please would you be able to implement this in the copter firmware. This would be useful because radios like the DJI Dt7 do not allow channel mixing even via hardware changes (I tried) I am buying a Taranis now anyway however im sure this would help other people have a smoother changeover from DJI products. Thanks!

**Comment by rmackay9** [comment] 2015-12-12 04:48
This is more a request for the copter software rather than the ground station so closing here.

It's also a duplicate of this issue: https://github.com/diydrones/ardupilot/issues/1974

Thanks for reporting in any case and using Copter!

**Closed by rmackay9** 2015-12-12 04:48 UTC
