### ISSUE TITLE
ARMING_CHECK checkboxes aren't displaying underlying value properly

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#912] opened 2015-06-27 10:39 UTC
![armingcheckbitmaskprob](https://cloud.githubusercontent.com/assets/1498098/8391614/29a971b8-1d04-11e5-8078-1eb6852c46a1.png)

**Comment by SkiTiSu** [comment] 2015-07-16 08:14
This number is defined differently in values and bitmask. In  "Standard Params", this number is understood as bitmask but also write as a value. I'd like to know how to distinguish them? (Because a Param only have one value)

**Comment by SkiTiSu** [comment] 2015-07-16 08:48
This number is defined differently in values and bitmask. In "Standard Params", this number is understood as bitmask but also write as a value. I'd like to know how to distinguish them? (Because a Param only have one value)

<Values>0:Disabled, 1:Enabled, -3:Skip Baro, -5:Skip Compass, -9:Skip GPS, -17:Skip INS, -33:Skip Params/Sonar, -65:Skip RC, 127:Skip Voltage</Values>
<Bitmask>0:All,1:Baro,2:Compass,3:GPS,4:INS,5:Parameters+Sonar,6:RC,7:Voltage</Bitmask>

**Comment by SkiTiSu** [comment] 2015-07-16 09:40
@rmackay9 I have fixed this issue, but still have a problem. The "Values" of "ARMING_CHECK" are not the index of 2, will it cause some problems? Thx.

**Comment by meee1** [comment] 2015-07-16 12:30
the fix for this is here
db25e202

**Closed by meee1** 2015-07-16 12:30 UTC
Labels: arducopter

**Comment by SkiTiSu** [comment] 2015-07-16 15:31
@meee1 db25e20 seems still have some problems:

For example, after I changed "ARMING_CHECK" to 4,
![11](https://cloud.githubusercontent.com/assets/8959735/8727015/f9476a46-2c0f-11e5-821a-f7654972ba39.jpg)
the checkboxes would not change in "Standard Params".
![12](https://cloud.githubusercontent.com/assets/8959735/8727016/fc6ee3b6-2c0f-11e5-97f1-5293f2b51dac.jpg)

Everytime we entered "Standard Params", the List of checkboxes will be double counting
![15](https://cloud.githubusercontent.com/assets/8959735/8727309/90f8309a-2c11-11e5-8c9b-f35f698ccc8d.jpg)

This time I only checked Baro, and click "Write Params" for many times, the value is accumulated into the max.
![16](https://cloud.githubusercontent.com/assets/8959735/8727372/e49c9c22-2c11-11e5-8cc2-9e17c7168ce3.jpg)
![17](https://cloud.githubusercontent.com/assets/8959735/8727373/e5189598-2c11-11e5-8bdc-9361af4c9b47.jpg)

I think the problem is caused here,
```csharp
if (items[0].GetType() == typeof (MavlinkCheckBoxBitMask))
{
    ((MavlinkCheckBoxBitMask) items[0]).ValueChanged -= Control_ValueChanged;
    ((MavlinkCheckBoxBitMask) items[0]).setup(x.Key, MainV2.comPort.MAV.param); // here
    ((MavlinkCheckBoxBitMask) items[0]).ValueChanged += Control_ValueChanged;
    return;
}
```
maybe we could not setup it everytime.

In d2b3792, I fixed them.

Thanks.
